Models/ErrorViewModel.cs
namespace RestaurantRaterMVC.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Restaurant/RestaurantCreate.cs
using System.ComponentModel.DataAnnotations;

namespace RestaurantRaterMVC.Models.Restaurant
{
    public class RestaurantCreate
    {
        [Required]
        [StringLength(100)]
        public string Name {get; set;}
        [Required]
        [StringLength(100)]
        public string Location {get; set;}
    }
}

Models/Restaurant/RestaurantDetail.cs
using System.ComponentModel.DataAnnotations;

namespace RestaurantRaterMVC.Models.Restaurant
{
    public class RestaurantDetail
    {
        public int Id {get; set;}
        public string Name { get; set; }
        public string Location { get; set; }
        [Display(Name = "Average Score")]
        public double Score { get; set; }

    }
}

Models/Restaurant/RestaurantListItem.cs
using System.ComponentModel.DataAnnotations;

namespace RestaurantRaterMVC.Models.Restaurant
{
    public class RestaurantListItem
    {
        public int Id {get; set;}
        public string Name {get; set;}
        [Display(Name = "Average Score")]
        public double Score {get; set;}
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using RestaurantRaterMVC.Models;

namespace RestaurantRaterMVC.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/RestaurantController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RestaurantRaterMVC.Data;
using RestaurantRaterMVC.Models.Restaurant;

namespace RestaurantRaterMVC.Controllers
{
    [Route("[controller]")]
    public class RestaurantController : Controller
    {
        private readonly ILogger<RestaurantController> _logger;
        private RestaurantDbContext _context;
        public RestaurantController(ILogger<RestaurantController> logger, RestaurantDbContext context)
        {
            _logger = logger;
            _context = context;
        }
        //[HttpGet]
        public async Task<IActionResult> Index() 
        {
            List<RestaurantListItem> restaurants = await _context.Restaurants
            .Include(r => r.Ratings)
            .Select(r => new RestaurantListItem()
            {
                Id = r.Id,
                Name = r.Name,
                Score = r.Score,
            }).ToListAsync();

            return View(restaurants);
        }

        [ActionName("Details")]
        public async Task<IActionResult> Restaurant(int id)
        {
            Restaurant restaurant = await _context.Restaurants
                .Include(r=> r.Ratings)
                .FirstOrDefaultAsync(r => r.Id == id);

            if (restaurant == null)
                return RedirectToAction(nameof(Index));
            
            RestaurantDetail restaurantDetail = new RestaurantDetail()
            {
                Id = restaurant.Id,
                Name = restaurant.Name,
                Location = restaurant.Location,
                Score = restaurant.Score
            };

            return View(restaurantDetail);
        }

        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(RestaurantCreate model)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.errorMessage = ModelState.FirstOrDefault().Value.Errors.FirstOrDefault().ErrorMessage;
                return View(model);
            }

            Restaurant restaurant = new Restaurant()
            {
                Name = model.Name,
                Location = model.Location,
            };

            _context.Restaurants.Add(restaurant);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Restaurant/Create.cshtml
@model RestaurantRaterMVC.Models.Restaurant.RestaurantCreate

@{
    ViewData["Title"] = "Create a Restaurant";
}

<h1>Create a Restaurant</h1>
<hr />

<form asp-action="Create">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Name" class="control-label"></label>
        <input asp-for="Name" class="form-control"/>
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
     <div class="form-group">
        <label asp-for="Location" class="control-label"></label>
        <input asp-for="Location" class="form-control"/>
        <span asp-validation-for="Location" class="text-danger"></span>
    </div>
</form>

<div class="form-group">
    <input type="submit" value="Create" class="btn btn-primary" />
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Restaurant/Detail.cshtml
@model RestaurantRaterMVC.Models.Restaurant.RestaurantDetail

@{
    ViewData["Title"] = Model.Name;
}

<h1>@Model.Name</h1>
<h4>Restaurant Details</h4>
<hr />

<dl class="row">
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Id)
    </dt>
    <dd class"col-sm-10>
        @Html.DisplayFor(model => model.Id)
    </dd>

    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Name)
    </dt>
    <dd class"col-sm-10>
        @Html.DisplayFor(model => model.Name)
    </dd>

    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Location)
    </dt>
    <dd class"col-sm-10>
        @Html.DisplayFor(model => model.Location)
    </dd>

    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Score)
    </dt>
    <dd class"col-sm-10>
        if (Model.Score > 0)
        {
            @Html.DisplayFor(modelItem => Model.Score)
        }
        else
        {
            <span>No Ratings Yet</span>
        }
    </dd>
</dl>

<div>
    <a asp-action="Edit" asp-route-id=@Model.Id>Edit</a>
    <a asp-action="Index">Back to List</a>
</div>

Views/Restaurant/Index.cshtml
@model IEnumerable<RestaurantRaterMVC.Models.Restaurant.RestaurantListItem>

@{
    ViewData["Title"] = "Restaurant Index";
}

<h1>Restaurant Index</h1>
<p>
    @Html.ActionLink("Create Restaurant", "Create")
</p>

<table class="table">
    <thead>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Score)
        </th>
        <th></th>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @if (item.Score > 0)
                    {
                    @Html.DisplayFor(modelItem => item.Name)
                    }
                    else
                    {
                        <span>No Ratings Yet</span>
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Score)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", "Restaurant", new {id = item.Id})
                    @Html.ActionLink("Details", "Details", "Restaurant", new {id = item.Id})
                    @Html.ActionLink("Delete", "Delete", "Restaurant", new {id = item.Id})
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RestaurantRaterMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RestaurantRaterMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RestaurantRaterMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - RestaurantRaterMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>